type GeneralAnswerCardProps = {
  query: string;
  answer: string;
  usedWebSearch: boolean;
  generatedAt?: string;
};

function formatAnswer(value: string): string[] {
  return value
    .split(/\n{2,}/)
    .map((section) => section.trim())
    .filter(Boolean);
}

export default function GeneralAnswerCard({
  query,
  answer,
  usedWebSearch,
  generatedAt,
}: GeneralAnswerCardProps) {
  const sections = formatAnswer(answer);

  const formattedTime = generatedAt
    ? new Intl.DateTimeFormat("en-GB", {
        dateStyle: "medium",
        timeStyle: "short",
      }).format(new Date(generatedAt))
    : null;

  return (
    <section className="mt-10 text-left">
      <div className="overflow-hidden rounded-[2rem] border border-white/20 bg-white shadow-2xl">
        <div className="bg-gradient-to-br from-blue-950 via-slate-950 to-slate-900 p-6 text-white sm:p-8">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-sm font-extrabold uppercase tracking-[0.22em] text-blue-200">
                Beacon Answer
              </p>

              <h2 className="mt-3 text-2xl font-black sm:text-3xl">
                A clear answer to your request
              </h2>
            </div>

            <div className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-extrabold uppercase tracking-[0.14em] text-blue-100 backdrop-blur">
              {usedWebSearch
                ? "Live web research used"
                : "Beacon AI"}
            </div>
          </div>

          <div className="mt-6 rounded-2xl border border-white/15 bg-white/10 p-5 backdrop-blur">
            <p className="text-xs font-extrabold uppercase tracking-[0.18em] text-blue-200">
              Your request
            </p>

            <p className="mt-2 text-lg font-bold leading-7 text-white">
              “{query}”
            </p>
          </div>
        </div>

        <div className="p-6 sm:p-8">
          <div className="space-y-5 text-base leading-8 text-slate-700">
            {sections.length > 0 ? (
              sections.map((section, index) => (
                <p key={`${index}-${section.slice(0, 24)}`}>
                  {section}
                </p>
              ))
            ) : (
              <p>
                Beacon could not produce a complete answer for this request.
              </p>
            )}
          </div>

          {usedWebSearch && (
            <div className="mt-8 rounded-2xl border border-blue-100 bg-blue-50 p-5">
              <p className="font-extrabold text-blue-950">
                Live information checked
              </p>

              <p className="mt-2 text-sm leading-6 text-blue-900">
                Beacon used current web research while preparing this answer.
                Prices, availability, rules and other changing information can
                still change, so check important details before acting.
              </p>
            </div>
          )}

          {!usedWebSearch && (
            <div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-5">
              <p className="font-extrabold text-slate-900">
                General guidance
              </p>

              <p className="mt-2 text-sm leading-6 text-slate-600">
                This answer was prepared using Beacon AI without live web
                research. Ask Beacon to check current information when timing,
                prices or availability matter.
              </p>
            </div>
          )}

          <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-slate-200 pt-5">
            <p className="text-sm font-semibold text-slate-500">
              {formattedTime
                ? `Generated ${formattedTime}`
                : "Generated by Beacon AI"}
            </p>

            <button
              type="button"
              onClick={() => {
                void navigator.clipboard.writeText(answer);
              }}
              className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-extrabold text-slate-800 transition hover:border-blue-300 hover:bg-blue-50"
            >
              Copy Answer
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}